SELECT *FROM PERSONAS	
CALL SPU_PERSONAS_REGISTRAR('Daniel','Fernandez','1999-06-11','934473365','M','','danielferq15@gmail.com','','');

CALL SPU_CLASIFICACION_REGISTRAR('Tv, Audio y Foto');
CALL SPU_CLASIFICACION_REGISTRAR('Electrohogar');
CALL SPU_CLASIFICACION_REGISTRAR('Celulares y Tablets');
CALL SPU_CLASIFICACION_REGISTRAR('Cómputo');
CALL SPU_CLASIFICACION_REGISTRAR('Consolas y Videojuegos');

CALL SPU_MODULO_REGISTRAR('Compras','','1');


SELECT *FROM categorias	



CALL SPU_MODULO_REGISTRAR('Dashboard','Dashboard','1');
CALL SPU_MODULO_REGISTRAR('Clasificación','','1');
CALL SPU_MODULO_REGISTRAR('Categoría ','','1');
CALL SPU_MODULO_REGISTRAR('Marca','','1');
CALL SPU_MODULO_REGISTRAR('Usuario','','1');
CALL SPU_MODULO_REGISTRAR('Rol','','1');
CALL SPU_MODULO_REGISTRAR('Configuración','','1');
CALL SPU_MODULO_REGISTRAR('Log','','1');
CALL SPU_MODULO_REGISTRAR('Parámetros','','1');
CALL SPU_MODULO_REGISTRAR('Presentación','','1');
CALL SPU_MODULO_REGISTRAR('Productos','','1');
CALL SPU_MODULO_REGISTRAR('Clientes','','1');
CALL SPU_MODULO_REGISTRAR('Provedores','','1');
CALL SPU_MODULO_REGISTRAR('Cajas','','1');
CALL SPU_MODULO_REGISTRAR('Compras','','1');
CALL SPU_MODULO_REGISTRAR('Ventas','','1');
CALL SPU_MODULO_REGISTRAR('Administrar Crédito','','1');
CALL SPU_MODULO_REGISTRAR('Cotizaciones','','1');
CALL SPU_MODULO_REGISTRAR('Apartados','','1');
CALL SPU_MODULO_REGISTRAR('Kardex','','1');
CALL SPU_MODULO_REGISTRAR('Monedas','','1');

SELECT *FROM modulos

CALL SPU_MARCA_REGISTRAR('Converse');
CALL SPU_MARCA_REGISTRAR('Renzo Costa');
CALL SPU_MARCA_REGISTRAR('LaLaLove');
CALL SPU_MARCA_REGISTRAR('GUCCI');
CALL SPU_MARCA_REGISTRAR('Capittana');
CALL SPU_MARCA_REGISTRAR('Camote Soup');
CALL SPU_MARCA_REGISTRAR('Butrich');
CALL SPU_MARCA_REGISTRAR('Nebula');
CALL SPU_MARCA_REGISTRAR('Umbro');
CALL SPU_MARCA_REGISTRAR('Agua Clara');
CALL SPU_MARCA_REGISTRAR('Merrell');
CALL SPU_MARCA_REGISTRAR('Steve Madden');
CALL SPU_MARCA_REGISTRAR('Chanel');
CALL SPU_MARCA_REGISTRAR('Louis Vuitton');
CALL SPU_MARCA_REGISTRAR('Gucci');
CALL SPU_MARCA_REGISTRAR('Christian Dior');
CALL SPU_MARCA_REGISTRAR('Versace');
CALL SPU_MARCA_REGISTRAR('Fendi');
CALL SPU_MARCA_REGISTRAR('Prada');
CALL SPU_MARCA_REGISTRAR('Balenciaga');
CALL SPU_MARCA_REGISTRAR('Nike');
CALL SPU_MARCA_REGISTRAR('Adidas');
CALL SPU_MARCA_REGISTRAR('Amazon Fashion');
CALL SPU_MARCA_REGISTRAR('Calvin Klein');
CALL SPU_MARCA_REGISTRAR('Lacoste');


SELECT *FROM marcas


SELECT * FROM presentaciones	
CALL SPU_PRESENTACION_REGISTRAR('Unidad','Und');
CALL SPU_PRESENTACION_REGISTRAR('Libra','Libra');
CALL SPU_PRESENTACION_REGISTRAR('Kilogramo','Kg');
CALL SPU_PRESENTACION_REGISTRAR('Caja','Caja');
CALL SPU_PRESENTACION_REGISTRAR('Paquete','Paq');
CALL SPU_PRESENTACION_REGISTRAR('Lata','Lat');
CALL SPU_PRESENTACION_REGISTRAR('Galon','Gal');
CALL SPU_PRESENTACION_REGISTRAR('Botella','Bot');
CALL SPU_PRESENTACION_REGISTRAR('Tira','Tira');
CALL SPU_PRESENTACION_REGISTRAR('Sobre','Sob');
CALL SPU_PRESENTACION_REGISTRAR('Bolsa','Bol');
CALL SPU_PRESENTACION_REGISTRAR('Saco','Saco');
CALL SPU_PRESENTACION_REGISTRAR('Tarjeta','tarjeta');

CALL SPU_CLASIFICACION_CBOLISTAR();
CALL SPU_CLASIFICACION_IDLISTAR('CL00000005');
SELECT *FROM categorias
SELECT *FROM clasificaciones
CALL SPU_CATEGORIA_IDLISTAR('CA00000002')